WITH FE AS
         (SELECT SUM(CODE) AS SKILL_CODE
          FROM SKILLCODES
          GROUP BY CATEGORY
          HAVING CATEGORY = 'Front End'),
     GRADE_TABLE AS
         (SELECT B.ID, (CASE
                            WHEN B.SKILL_CODE & FE.SKILL_CODE
             AND B.SKILL_CODE &
                (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
            WHEN B.SKILL_CODE &
                (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
            WHEN B.SKILL_CODE & FE.SKILL_CODE THEN 'C' END) AS GRADE
          FROM FE, DEVELOPERS AS B)

SELECT A.GRADE, A.ID, B.EMAIL
FROM GRADE_TABLE AS A
         JOIN DEVELOPERS AS B ON A.ID = B.ID
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;