SELECT H.FLAVOR
FROM FIRST_HALF AS H
         JOIN (SELECT FLAVOR, TOTAL_ORDER FROM JULY) AS J
              ON H.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(H.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC LIMIT 3;